### ISSUE TITLE
vs developit/redaxios?

### ISSUE THREAD

**Issue by tomByrer** [donavon/thwack#20]
https://github.com/developit/redaxios

What I see on surface:

+ redaxios is smaller
+ thwack has TS types
+ redaxios has 1:1 API parity
+ thwack has extra events for convenience

What I'm really interested in is speed; @developit is a great dev but he mega-focuses on file size, while I prefer a focus on execution speed (use case: serverless pricing may go into the ms; Cloudflare Workers are capped 5-25ms.)

edit: added to per comment below

**Comment by developit** [comment]
My 2 cents: I don't think there's enough going on in any of these minimal fetch wrappers to make a measurable difference in runtime performance. Requesting, downloading and parsing network requests is always going to take many orders of magnitude longer than merging a few objects and firing some events.

I wasn't aware of this library, but I like the events it fires and use something very similar in all of my stuff (and I keep writing them one-off every time...)

**Comment by donavon** [comment]
And I wasn't aware of @developit's redaxios. It's tiny.

As Jason has said, performance is going to be roughly the same, no matter what package you use. `thwack@next` is going to have a more robust `addEventListener` interface, with multiple level request mocking, replacing, blocking, etc, but probably not needed by most users.

redaxios is a good ultra-minimal alternative, although not 100% axios compatible (lacking `interceptors`), but again, probably not needed by most apps.

BTW, I have a TODO to look into using the EventTarget interface to lower my overhead.

**Comment by developit** [comment]
@donavon sounds like some nice improvements.

RE EventTarget - I've tried a bunch of different techniques for reusing it as a generalized event interface, and never found a way that was materially better than a tight first party implementation. I'd have to peek at the code again to see how yours is implemented, but you might be able lift the optimizations from [mitt](https://github.com/developit/mitt/src/index.js), which should be about as small as you can get in JS.
