### ISSUE TITLE
Abort requests in nodejs

### ISSUE THREAD

**Issue by ryhinchey** [donavon/thwack#25]
Using AbortController works great in the browser and there’s a node version recommended in the node-fetch docs.  I think it’d be nice to have a standard way to abort across the browser and node.

Happy to work on a pr!

**Comment by donavon** [comment]
I don't want to bloat Thwack with anything Node specific. If there were some sort of AbortController polyfill that we could put into `thwack/node` then I'd be all for it.

**Comment by donavon** [comment]
Seems to me that a person could use an AbortController polyfill such as [node-abort-controller](https://github.com/southpolesteve/node-abort-controller) and be done with it. That way I'm not forcing any particular AbortController on them if they don't need it. Maybe we just go that way and update the docs to say as much?

**Comment by ryhinchey** [comment]
> Seems to me that a person could use an AbortController polyfill such as [node-abort-controller](https://github.com/southpolesteve/node-abort-controller) and be done with it. That way I'm not forcing any particular AbortController on them if they don't need it. Maybe we just go that way and update the docs to say as much?

yah I think that's the right move.  I'll make a PR now updating the docs and will close this issue. Thanks!
