### ISSUE TITLE
Types aren't detected when importing thwack/node

### ISSUE THREAD

**Issue by iansu** [donavon/thwack#26]
When using TypeScript and Node.js the types aren't detected. Copying the `types` directory into the `node` directory solves this problem. I'm sure there's a better way to fix this I'm just not sure what it is.

**Comment by donavon** [comment]
try creating a file `/node/package.json` with the following: 🤷‍♂️

```js
{
  "types": "../types/index.d.ts",
}
```

**Comment by iansu** [comment]
That seems to also work.

**Comment by donavon** [comment]
I'll add it and bump the build.

**Comment by donavon** [comment]
published to npm as `thwack@0.3.1`

**Comment by ericchernuka** [comment]
I think this might have crept back in after the library was re-written? The types are no longer available for node/node10.
