### ISSUE TITLE
How can i cancel request, and listen to canceled event and use it with react hooks like logging example

### ISSUE THREAD

**Issue by EminQasimov** [donavon/thwack#5]

**Comment by aviskarkc10** [comment]
@donavon are there any plans to implement this?

**Comment by MiroDojkic** [comment]
@EminQasimov since `thwack` seems to pass through options to `fetch` call, you could probably use `AbortController` to cancel requests by passing its `signal`:
```javascript
const controller = new AbortController();
const { signal } = controller;

thwack(url, { signal })
  .then(handleResponse)
  .catch(handleError);

controller.abort();
```

You can listen to `abort` event on `signal` too:
```javascript
signal.addEventListener('abort', handleAbort);
```

**Comment by aviskarkc10** [comment]
@MiroDojkic yeah that should probably work.

**Comment by karlhorky** [comment]
I've added this as a recipe in #14.
